"""
server.py — Deploy this on Render (free tier)
Handles: Face identification, RAG from aiml.pccoepune.com, LLM response via Groq

Environment variables to set in Render dashboard:
    GROQ_API_KEY=your_groq_key
    CRAWL_SECRET=any_secret_string_you_choose   (to protect /crawl endpoint)

File needed in same directory:
    encodings.pkl  (generated by train_encodings.py on your PC)p
"""

import os
import re
import json
import time
import pickle
import hashlib
import logging
import asyncio
import numpy as np
from typing import Optional
from pathlib import Path
from collections import deque

import httpx
from bs4 import BeautifulSoup
from fastapi import FastAPI, HTTPException, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from pinecone import Pinecone, ServerlessSpec
from groq import Groq

# ─── Logging ──────────────────────────────────────────────────────────────────
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger(__name__)

# ─── Config ───────────────────────────────────────────────────────────────────
ENCODINGS_FILE   = "encodings.pkl"
WEBSITE_CACHE    = "website_chunks.json"
FACE_THRESHOLD   = 0.5          # lower = stricter match
CHUNK_SIZE       = 400          # chars per RAG chunk
MAX_RAG_CHUNKS   = 5            # chunks sent to LLM
CRAWL_MAX_PAGES  = 60           # max pages to crawl
GROQ_MODEL       = "llama-3.1-8b-instant"   # fast & free on Groq

SEED_URLS = [
    "https://aiml.pccoepune.com/",
    "https://aiml.pccoepune.com/aiml-hod",
    "https://aiml.pccoepune.com/faculty-profile",
    "https://aiml.pccoepune.com/about",
    "https://aiml.pccoepune.com/research-area-sigs",
    "https://aiml.pccoepune.com/stud-activities",
    "https://aiml.pccoepune.com/placement",
    "https://aiml.pccoepune.com/contact"
]

# Greeting map — edit freely. Keys are lowercase trigger phrases.
GREETING_MAP = {
    "good morning"  : "Good morning, {name}! Have a great day ahead!",
    "good afternoon": "Good afternoon, {name}! Hope your day is going well!",
    "good evening"  : "Good evening, {name}! Hope you had a wonderful day!",
    "hello"         : "Hello, {name}! Nice to meet you!",
    "hi"            : "Hi there, {name}! Great to see you!",
    "how are you"   : "I'm doing great, {name}! Hope you are too!",
    "bye"           : "Goodbye, {name}! See you soon!",
    "good night"    : "Good night, {name}! Sweet dreams!",
    "thank you"     : "You're welcome, {name}! Happy to help!",
    "thanks"        : "Anytime, {name}! Take care!",
}

# ─── App ──────────────────────────────────────────────────────────────────────
app = FastAPI(title="RPi AI Server")
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_methods=["*"], allow_headers=["*"])

groq_client: Optional[Groq] = None
face_encodings: list = []
face_names: list = []
rag_chunks: list[str] = []       # plain text chunks
rag_index: Optional[object] = None   # Pinecone index object
rag_vectors: Optional[np.ndarray] = None

# ─── Startup ──────────────────────────────────────────────────────────────────
@app.on_event("startup")
async def startup():
    global groq_client, face_encodings, face_names

    api_key = os.getenv("GROQ_API_KEY", "")
    if api_key:
        groq_client = Groq(api_key=api_key)
        log.info("Groq client ready")
    else:
        log.warning("GROQ_API_KEY not set — LLM disabled")

    # Load face encodings
    if Path(ENCODINGS_FILE).exists():
        with open(ENCODINGS_FILE, "rb") as f:
            data = pickle.load(f)
        face_encodings = data["encodings"]
        face_names     = data["names"]
        log.info(f"Loaded {len(face_names)} face encodings: {face_names}")
    else:
        log.warning(f"'{ENCODINGS_FILE}' not found — face ID disabled")

    # Load or trigger crawl
    if Path(WEBSITE_CACHE).exists():
        load_rag_from_cache()
    else:
        log.info("No website cache found — triggering crawl in background")
        asyncio.create_task(crawl_and_index())

# ─── Models ───────────────────────────────────────────────────────────────────
class FaceRequest(BaseModel):
    encoding: list[float]   # 128-dim face encoding from RPi

class ChatRequest(BaseModel):
    name: str               # from /identify
    text: str               # STT result from RPi

class FaceResponse(BaseModel):
    name: str
    confidence: float

class ChatResponse(BaseModel):
    reply: str
    source: str             # "greeting" | "rag" | "fallback"

# ─── Face Identification ──────────────────────────────────────────────────────
@app.post("/identify", response_model=FaceResponse)
def identify_face(req: FaceRequest):
    if not face_encodings:
        return FaceResponse(name="Guest", confidence=0.0)

    query = np.array(req.encoding, dtype=np.float64)
    distances = [
        np.linalg.norm(query - np.array(enc, dtype=np.float64))
        for enc in face_encodings
    ]
    best_idx  = int(np.argmin(distances))
    best_dist = float(distances[best_idx])

    if best_dist > FACE_THRESHOLD:
        return FaceResponse(name="Guest", confidence=round(1 - best_dist, 3))

    return FaceResponse(
        name=face_names[best_idx].replace("_", " ").title(),
        confidence=round(1 - best_dist, 3)
    )

# ─── Chat / RAG ───────────────────────────────────────────────────────────────
@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    text_lower = req.text.strip().lower()
    name = req.name or "Guest"

    # 1. Check greeting map first (zero latency)
    for trigger, template in GREETING_MAP.items():
        if trigger in text_lower:
            reply = template.format(name=name)
            return ChatResponse(reply=reply, source="greeting")

    # 2. RAG + LLM
    if groq_client and rag_chunks:
        context = retrieve_chunks(req.text)
        prompt = build_prompt(name, req.text, context)
        try:
            completion = groq_client.chat.completions.create(
                model=GROQ_MODEL,
                messages=[{"role": "user", "content": prompt}],
                max_tokens=200,
                temperature=0.4,
            )
            reply = completion.choices[0].message.content.strip()
            # Personalise if name mentioned
            if name != "Guest" and name not in reply:
                reply = f"{name}, {reply}"
            return ChatResponse(reply=reply, source="rag")
        except Exception as e:
            log.error(f"Groq error: {e}")

    # 3. Fallback
    return ChatResponse(
        reply=f"Sorry {name}, I didn't quite catch that. Could you repeat?",
        source="fallback"
    )

# ─── Admin: Trigger crawl ─────────────────────────────────────────────────────
@app.post("/crawl")
async def trigger_crawl(background_tasks: BackgroundTasks, secret: str = ""):
    expected = os.getenv("CRAWL_SECRET", "changeme")
    if secret != expected:
        raise HTTPException(status_code=403, detail="Invalid secret")
    background_tasks.add_task(crawl_and_index)
    return {"status": "crawl started in background"}

@app.get("/health")
def health():
    return {
        "faces": len(face_names),
        "rag_chunks": len(rag_chunks),
        "groq": groq_client is not None,
    }

# ─── RAG Utilities ────────────────────────────────────────────────────────────
def text_to_vector(text: str, dim: int = 128) -> np.ndarray:
    """
    Lightweight hashing-based vectorizer — no heavy ML model needed.
    Deterministic: same text → same vector. Good enough for keyword-style retrieval.
    """
    vec = np.zeros(dim, dtype=np.float32)
    words = re.findall(r"\w+", text.lower())
    for word in words:
        h = int(hashlib.md5(word.encode()).hexdigest(), 16)
        idx = h % dim
        vec[idx] += 1.0
    norm = np.linalg.norm(vec)
    if norm > 0:
        vec /= norm
    return vec

def build_vector_index(chunks: list[str]):
    """Create / populate a Pinecone index from `chunks`.
    Requires `PINECONE_API_KEY` in environment. Serverless region is set
    via `ServerlessSpec` when creating the index.
    """
    global rag_index
    dim = 128
    api_key = os.getenv("PINECONE_API_KEY", "")
    index_name = os.getenv("PINECONE_INDEX_NAME", "aiml-rag")

    if not api_key:
        log.warning("PINECONE_API_KEY not set — vector DB disabled")
        return

    try:
        pc = Pinecone(api_key=api_key)
        existing = pc.list_indexes().names()
        if index_name not in existing:
            pc.create_index(
                name=index_name,
                dimension=dim,
                metric="cosine",
                spec=ServerlessSpec(cloud="aws", region="us-east-1"),
            )
        index = pc.Index(index_name)

        # upsert in batches
        to_upsert = []
        for i, c in enumerate(chunks):
            vec = text_to_vector(c, dim).astype(float).tolist()
            meta = {"text": c}
            to_upsert.append((f"chunk-{i}", vec, meta))

        # Pinecone accepts batches; do in chunks of 100
        batch_size = 100
        for i in range(0, len(to_upsert), batch_size):
            batch = to_upsert[i : i + batch_size]
            index.upsert(vectors=batch)

        rag_index = index
        log.info(f"Pinecone index ready: {len(chunks)} chunks -> index '{index_name}'")
    except Exception as e:
        log.error(f"Failed to initialize Pinecone index: {e}")

def retrieve_chunks(query: str, k: int = MAX_RAG_CHUNKS) -> str:
    if rag_index is None or not rag_chunks:
        return ""
    qvec = text_to_vector(query).astype(float).tolist()
    k    = min(k, len(rag_chunks))
    try:
        resp = rag_index.query(vector=qvec, top_k=k, include_metadata=True)
        matches = resp.get("matches", []) if isinstance(resp, dict) else resp.matches
        texts = []
        for m in matches:
            meta = m.get("metadata") if isinstance(m, dict) else getattr(m, "metadata", None)
            if meta and "text" in meta:
                texts.append(meta["text"])
        return "\n\n".join(texts)
    except Exception as e:
        log.error(f"Pinecone query failed: {e}")
        return ""

def load_rag_from_cache():
    global rag_chunks
    with open(WEBSITE_CACHE, "r", encoding="utf-8") as f:
        rag_chunks = json.load(f)
    build_vector_index(rag_chunks)
    log.info(f"RAG loaded from cache: {len(rag_chunks)} chunks")

def chunk_text(text: str, size: int = CHUNK_SIZE) -> list[str]:
    sentences = re.split(r'(?<=[.!?])\s+', text)
    chunks, current = [], ""
    for sent in sentences:
        if len(current) + len(sent) < size:
            current += " " + sent
        else:
            if current.strip():
                chunks.append(current.strip())
            current = sent
    if current.strip():
        chunks.append(current.strip())
    return chunks

def build_prompt(name: str, question: str, context: str) -> str:
    return f"""You are a helpful assistant for PCCOE's AI & ML department (aiml.pccoepune.com).
The person in front of you is named {name}. Answer their question using the provided context.
Be concise (2-3 sentences max) since the response will be spoken aloud via text-to-speech.

Context from the department website:
{context}

{name} asks: {question}

Answer:"""

# ─── Web Crawler ──────────────────────────────────────────────────────────────
async def crawl_and_index():
    global rag_chunks
    log.info("Starting website crawl...")
    all_chunks = []
    visited    = set()
    queue      = deque(SEED_URLS)
    base_domain = "aiml.pccoepune.com"

    async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
        while queue and len(visited) < CRAWL_MAX_PAGES:
            url = queue.popleft()
            if url in visited:
                continue
            visited.add(url)

            try:
                resp = await client.get(url)
                if resp.status_code != 200:
                    continue
                soup = BeautifulSoup(resp.text, "html.parser")

                # Remove nav/footer/script noise
                for tag in soup(["script", "style", "nav", "footer", "header", "aside"]):
                    tag.decompose()

                text = soup.get_text(separator=" ", strip=True)
                text = re.sub(r'\s{2,}', ' ', text).strip()

                if len(text) > 100:
                    chunks = chunk_text(text)
                    # Prefix each chunk with URL for context
                    prefixed = [f"[Source: {url}]\n{c}" for c in chunks]
                    all_chunks.extend(prefixed)
                    log.info(f"  ✓ {url} → {len(chunks)} chunks")

                # Discover links
                for a in soup.find_all("a", href=True):
                    href = a["href"].strip()
                    if href.startswith("/"):
                        full = f"https://{base_domain}{href}"
                    elif href.startswith(f"https://{base_domain}"):
                        full = href
                    else:
                        continue
                    full = full.split("#")[0].rstrip("/")
                    if full not in visited and full not in queue:
                        queue.append(full)

                await asyncio.sleep(0.3)   # polite delay

            except Exception as e:
                log.warning(f"  ✗ Failed {url}: {e}")

    rag_chunks = all_chunks
    with open(WEBSITE_CACHE, "w", encoding="utf-8") as f:
        json.dump(all_chunks, f, ensure_ascii=False)

    build_vector_index(rag_chunks)
    log.info(f"Crawl complete: {len(visited)} pages, {len(rag_chunks)} chunks saved")
